server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INFO/views
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123.com
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
# 日志配置

#logging:
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB