server:
  port: 8080


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # 主库数据源
    url: jdbc:mysql://192.168.124.2:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    #        url: jdbc:mysql://192.168.101.29:3306/miaofan?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123.com


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


